// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzhMKhVLmCqiWqFpcJ-U3EI-k0MnIz0C8',
    appId: '1:645563107833:web:95f9222c17bfa447fd9528',
    messagingSenderId: '645563107833',
    projectId: 'fir-test-app-e8f04',
    authDomain: 'fir-test-app-e8f04.firebaseapp.com',
    storageBucket: 'fir-test-app-e8f04.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqVsofl1vNbe-t1PHx7r8cjf1oZS1ijWM',
    appId: '1:645563107833:android:76bb1d047da01807fd9528',
    messagingSenderId: '645563107833',
    projectId: 'fir-test-app-e8f04',
    storageBucket: 'fir-test-app-e8f04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUeHpTmYc5qxDs7QxjHRLFze7VWRiuov0',
    appId: '1:645563107833:ios:9e58006184dcb365fd9528',
    messagingSenderId: '645563107833',
    projectId: 'fir-test-app-e8f04',
    storageBucket: 'fir-test-app-e8f04.appspot.com',
    iosClientId: '645563107833-iaf1et9e67i4npaaegg5mm3p8344j3bv.apps.googleusercontent.com',
    iosBundleId: 'az.kamran.flutterFirebaseApp',
  );
}
